### ISSUE TITLE
Make "Selected" recipe button a vibrant color

### ISSUE THREAD

**Issue by kitblake** [dexlab-io/ddai-frontend#29]
When a user is not logged in (with a wallet), all the "Select" buttons are black. When a wallet is connected, which contains DAI, then the "Earn DAI" recipe button is selected by default (nice! :)

The button says "Selected" but it's gray. It looks 'grayed out', like the "DISABLED" buttons below. If it was a vibrant color it would be more obvious that it's active. 

The magenta background of the "address+network" label in the header would make a nice visual connection. If that's too vibrant, that dDAI purple would work too.

**Comment by dimarconicola** [comment]
@kitblake thanks for the suggestion. We're going to push this on the next PR.
